### ISSUE TITLE
Organize and triage code TODOs into github issue

### ISSUE THREAD

**Issue by Zonr0** [cwtools/cwtools-ck3-config#8]
There are a lot of todos in code without a lot of external visibility unless actively searching from them. It would behoove us to move them to a more visible spot on github to track them in one place. Checked box means the item has either been addressed in code or documented on the issue tracker.

- [x]  Get TODOs from code
- [ ] Separate out into issues, combine as makes sense
  - [ ] chance_weight.cwt
      - [ ] L8: `# TODO: Figure out if the chance-weight difference is really needed`
      - [ ] L11, L28: `# TODO: Requires further testing, might necessiate splitting into chance_block and chance_block_with_base or something`
  - [ ] list_effects.cwt
      - [ ] Over many order_by keys: `# TODO: Work out what exactly this is restricted to`
  - [ ] activities.cwt
       - [ ] Figure and confirm bounds of values for 3 keys
       - [ ] Figure out and confirm default values for 2 keys
       - [ ] Find and confirm cardinality for 3 keys
       - [ ] L28: `# TODO: alias for colour; probably not as rigid as activities make it look (see interface files for comp.)`
   - [ ] ai_goaltypes.cwt
       - [ ] L1: `# TODO: This ~~article~~ type is a stub. You can help CWTools by expanding it.`
   - [x] bookmarks.cwt
       - [x] L18:`# TODO: figure out, [default] confirm uniqueness`
       - [x] L23:`# TODO: figure out [start_date]`
       - [x] L26:`# TODO: figure out [recommended]`
       - [x] L31:`# TODO: figure out, confirm cardinality, see if it's not a target for an alias [character]`
       - [x] L36:`dynasty_splendor_level = int[0..inf] # TODO: confirm bounds`
       - [x] L41:`type = enum[genders] # TODO: dig into this; something tells me this can be scripted to be more than just male/female`
       - [x] L42:`birth = date_field # TODO: see if it can be made to validate to be before the given start_date for the bookmark? Probably not worth the effort`
       - [x] L43:`history_id = int[1..inf] # TODO: confirm bounds`
       - [x] L49:`int[1..inf] # TODO: confirm bounds`
       - [x] L52:`# TODO: see if I can remember how to make it with subtypes so that I don't need to duplicate stuff :D [sub character]`
  - [ ] buildings.cwt
       - [ ] L7:`# TODO add subtype for pdxmesh vs entity`
       - [ ] L131:`# TODO: more detailed flags`
  - [ ] deathreasons.cwt
       - [ ] Icon
  - [ ] lifestyles.cwt
       - [ ] Icon
  - [ ] modifier_container.cwt
       - [ ] Icon
  - [ ] opinion_modifiers.cwt
       - [ ] L1:`# WISHLIST still: add ways to ensure a type has definitions for specified hardcoded names; for example, "opinion_war" must exist as an opinion type`
       - [ ] L2:`# TODO: There's a single "negative_test" that uses a "months" parameter but we'll need to check if it's legacy or actually a thing`
  - [ ] scripted_effects.cwt
       - [ ] L29:`# Todo: Make sure this works [alias for scripted effect]`
  - [ ] scripted_triggers.cwt
       - [ ] L6:`#Todo: Make sure this works [alias for scripted trigger]`
  - [ ] traits.cwt
       - [ ] `TODO: It might make sense to move many of these fields into a full alias for character_modifier. They are re-used in many places.` (Done needs comment removed)
       - [ ] `# TODO: Many of these (effects) seem like they're possibly soft-coded.`
       - [ ] `# TODO: Can some of these be replaced with keyed templates?` (Done, needs comment removed)
       - [ ] L89:`#TODO: Make [ililegitimate_bast... and legitimate-bast...] mutually exclusive
       - [ ] L145:`# TODO: Implement dna_modifiers. Probably as an alias.`
       - [ ] L218:`# TODO: Anything that can refer to a trait can refer to a group. Is there some way we can use this to mark a type name too?` (Done, needs comment removed)
       - [ ] L222:`#TODO: Does [level key] require group? Test with error log to confirm.`
       - [ ] L251:`# TODO: Require at least one trait or trait group`
       - [ ] L279:`#TODO: These are supposed to be linked to the parameters in doctrines. This means parameters in doctrines should probably be refactored to a type.`
  - [ ] religions.cwt
       - [ ] L11:`#TODO: Actually match these with defined traits.` (Done. Needs comment removed)
       - [ ] L55:`#TODO: Script check to make sure gfx/ui stuff is present in either the family, religion, or faith.`
       - [ ] L124:`#TODO: Implement coat of arms and regiments` (Partially done)
  - [ ] interface.cwt
       - [ ] L23:`#TODO: group cardinality` (percent coords)
       - [ ] Many gui loc string todos
       - [ ] Many sound todos
       - [ ] Several shader todos
  - [ ] windows.old
       - [ ] Many gui loc string todos
  - [ ] triggers.fsx
       - [ ] L256: `# TODO: Work out what exactly this is restricted to`

**Comment by Zonr0** [comment]
Bookmark todos documented in #10
