### ISSUE TITLE
Open issues for tracking scope and prepare for contributions

### ISSUE THREAD

**Issue by Zonr0** [cwtools/cwtools-ck3-config#9]
Especially as more people start contributing, it'll be very helpful to document areas that need to be implemented. This should help new contributors easily see work that needs done, and hopefully prevent duplication of work. Initial issues will probably be for draft level completion that covers most common cases but maybe not complicated rules or full validation checks for difficult validations. In general, I'm expecting about 3 regular contributors, a smattering of people submitting PRs for rules that they write while working on their own mods (and who generally won't be closely updating progress on the tracker), people who just file issues for false positives/false negatives, and people who just want to track development and know whats implemented.

There are two main options that I can think of to track this:

1) Vanilla script passing. Progress is measured by getting vanilla files to properly validate with minimal false positives. This works as a concrete, tangible goal and is a good measure of project progress. Bonus points for finding legitimate vanilla bugs. Having a 'standard' set of files is helpful for keeping a standardized set of test cases, and guarantees an acceptable level of functionality for end users even if not all rules are implemented. This does run the issue however of some possible duplication of effort as getting files to validate might require dipping into tangentially related areas. This could possibly result in work duplication among core contributors if good communication isn't followed. This would more closely follow one-off contributions. It would require PR reviewers to fetch the branch and test it against the vanilla files.

2) .cwt completion. Track purely on the .cwt files and types that need a .cwt; combine sub-folders into a single issue. This keeps things isolated for better or for worse. It lacks the standardized test cases, and leads to very abstracted work that feels divorced from actual use. This doesn't seem like it would fit well with the workflow of that type of contributor, but would be easier to mark issues completed.

After typing it out, I'm very much leaning towards 1, and will probably implement things that way. Other than that, we should probably build out some issue infrastructure and repository QoL things.

- [x] Create issue labels for common issue types. Off the top of my head: false positive/false negative, great first contribution, implementation, meta/project management, refactor, polish/misc. Does it make sense to split implementation into fresh or draft implementation and subsequent passes?
- [ ] Create issue templates where it makes sense.
   - [ ] false positives/negatives
   - [ ] new implementation (for easier automation)
- [x] Record issues for each part of the rules scope. It may be possible to partially automate this.
- [ ] Create some milestones as goals. eg. Core rules, common rules, full vanilla validation, maybe an end of September goal?
- [ ] (Maybe) Pull request template
- [ ] Write CONTRIBUTING.md
- [ ] Link to new shiny github.io parent project website.
- [ ] Clarify in parent/sibling projects that this is the repository to go for ck3 specific rule issues.

**Comment by Zonr0** [comment]
Working on a small automation tool to post the issues.
